cc=gcc
CFLAGS = -Wall
criaFifo: criaFifo.c 
escreveFifo: escreveFifo.c 
leFifo: leFifo.c
ex2: ex2.c



all: criaFifo escreveFifo leFifo ex2

clean:
	rm criaFifo
	rm escreveFifo
	rm leFifo
	rm ex2