cc=gcc
CFLAGS = -Wall
myCopy: myCopy.c
myCat: myCat.c
myReadln:myReadln.c
myReadln2:myReadln2.c
myNl:myNl.c
pessoas:pessoas.c

all: myCopy myCat myReadln myNl myReadln2 pessoas
clean:
	rm myCopy
	rm myCat
	rm myNl
	rm myReadln
	rm myReadln2
	rm pessoas
	rm pessoas.txt
